// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pos/pos.proto

package go_micro_srv_pos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pos struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos) Reset()         { *m = Pos{} }
func (m *Pos) String() string { return proto.CompactTextString(m) }
func (*Pos) ProtoMessage()    {}
func (*Pos) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a50fac5e0f00a8, []int{0}
}

func (m *Pos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos.Unmarshal(m, b)
}
func (m *Pos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos.Marshal(b, m, deterministic)
}
func (m *Pos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos.Merge(m, src)
}
func (m *Pos) XXX_Size() int {
	return xxx_messageInfo_Pos.Size(m)
}
func (m *Pos) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos.DiscardUnknown(m)
}

var xxx_messageInfo_Pos proto.InternalMessageInfo

func (m *Pos) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pos) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pos) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Pos                  *Pos     `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a50fac5e0f00a8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetPos() *Pos {
	if m != nil {
		return m.Pos
	}
	return nil
}

func init() {
	proto.RegisterType((*Pos)(nil), "go.micro.srv.pos.Pos")
	proto.RegisterType((*Response)(nil), "go.micro.srv.pos.Response")
}

func init() { proto.RegisterFile("proto/pos/pos.proto", fileDescriptor_10a50fac5e0f00a8) }

var fileDescriptor_10a50fac5e0f00a8 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x6d, 0x2b, 0xb5, 0x1d, 0x41, 0x64, 0x44, 0x09, 0x3d, 0x95, 0x5e, 0xec, 0x29, 0x42,
	0x7d, 0x01, 0xc5, 0xb3, 0x52, 0xe2, 0x13, 0xd4, 0x74, 0x90, 0x1c, 0xda, 0x09, 0x99, 0xd2, 0xe7,
	0x5f, 0x9a, 0xdd, 0x5e, 0x76, 0xf7, 0x10, 0xc8, 0xff, 0x33, 0xf3, 0xf1, 0x0d, 0x3c, 0xf9, 0xc0,
	0x0b, 0xbf, 0x79, 0x96, 0xed, 0xe9, 0x98, 0xf0, 0xf1, 0x9f, 0xf5, 0xe4, 0x6c, 0x60, 0x2d, 0x61,
	0xd5, 0x9e, 0xa5, 0xf9, 0x84, 0xac, 0x67, 0xc1, 0x07, 0x48, 0xdd, 0xa8, 0x92, 0x3a, 0x69, 0x4b,
	0x93, 0xba, 0x11, 0x11, 0x6e, 0xe7, 0x61, 0x22, 0x95, 0xc6, 0x26, 0xfe, 0xf1, 0x05, 0xf2, 0xc1,
	0x2e, 0x6e, 0x25, 0x95, 0xd5, 0x49, 0x5b, 0x98, 0x53, 0x6a, 0xbe, 0xa1, 0x30, 0x24, 0x9e, 0x67,
	0x21, 0x54, 0x70, 0x67, 0x03, 0x0d, 0x0b, 0x1d, 0x61, 0x85, 0xd9, 0x23, 0xbe, 0x42, 0xe6, 0x59,
	0x22, 0xf0, 0xbe, 0x7b, 0xd6, 0xe7, 0x22, 0xba, 0x67, 0x31, 0xdb, 0x44, 0xf7, 0x03, 0xd0, 0xb3,
	0xfc, 0x52, 0x58, 0x9d, 0x25, 0xfc, 0x80, 0xf2, 0x2b, 0x12, 0x36, 0xcb, 0xeb, 0x6b, 0x55, 0x75,
	0x59, 0xef, 0x42, 0xcd, 0xcd, 0x5f, 0x1e, 0x4f, 0x7f, 0x3f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x01,
	0x3a, 0x3a, 0xc0, 0x11, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PosServiceClient is the client API for PosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PosServiceClient interface {
	CreatePos(ctx context.Context, in *Pos, opts ...grpc.CallOption) (*Response, error)
}

type posServiceClient struct {
	cc *grpc.ClientConn
}

func NewPosServiceClient(cc *grpc.ClientConn) PosServiceClient {
	return &posServiceClient{cc}
}

func (c *posServiceClient) CreatePos(ctx context.Context, in *Pos, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.pos.PosService/CreatePos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PosServiceServer is the server API for PosService service.
type PosServiceServer interface {
	CreatePos(context.Context, *Pos) (*Response, error)
}

func RegisterPosServiceServer(s *grpc.Server, srv PosServiceServer) {
	s.RegisterService(&_PosService_serviceDesc, srv)
}

func _PosService_CreatePos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServiceServer).CreatePos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.pos.PosService/CreatePos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServiceServer).CreatePos(ctx, req.(*Pos))
	}
	return interceptor(ctx, in, info, handler)
}

var _PosService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.pos.PosService",
	HandlerType: (*PosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePos",
			Handler:    _PosService_CreatePos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pos/pos.proto",
}
